/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.service.support.servicesupport_be_v1.web.api;

import com.service.support.servicesupport_be_v1.web.model.OwnerCompanyEmployee;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-10-17T20:54:47.397666300+02:00[Europe/Budapest]")
@Validated
@Tag(name = "owner_company_employee", description = "the owner_company_employee API")
public interface OwnerCompanyEmployeeApi {

    /**
     * GET /owner-company-employees : Get all employees
     *
     * @return List of employees (status code 200)
     */
    @Operation(
        operationId = "ownerCompanyEmployeesGet",
        summary = "Get all employees",
        tags = { "owner_company_employee" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of employees", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = OwnerCompanyEmployee.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/owner-company-employees",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<OwnerCompanyEmployee>> ownerCompanyEmployeesGet(
        
    );


    /**
     * DELETE /owner-company-employees/{id} : Delete employee
     *
     * @param id  (required)
     * @return Deleted (status code 204)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "ownerCompanyEmployeesIdDelete",
        summary = "Delete employee",
        tags = { "owner_company_employee" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Deleted"),
            @ApiResponse(responseCode = "404", description = "Not found")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/owner-company-employees/{id}"
    )
    
    ResponseEntity<Void> ownerCompanyEmployeesIdDelete(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );


    /**
     * GET /owner-company-employees/{id} : Get employee by ID
     *
     * @param id  (required)
     * @return Employee found (status code 200)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "ownerCompanyEmployeesIdGet",
        summary = "Get employee by ID",
        tags = { "owner_company_employee" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Employee found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OwnerCompanyEmployee.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not found")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/owner-company-employees/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<OwnerCompanyEmployee> ownerCompanyEmployeesIdGet(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );


    /**
     * PUT /owner-company-employees/{id} : Update employee
     *
     * @param id  (required)
     * @param ownerCompanyEmployee  (required)
     * @return Updated (status code 200)
     */
    @Operation(
        operationId = "ownerCompanyEmployeesIdPut",
        summary = "Update employee",
        tags = { "owner_company_employee" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OwnerCompanyEmployee.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/owner-company-employees/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<OwnerCompanyEmployee> ownerCompanyEmployeesIdPut(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
        @Parameter(name = "OwnerCompanyEmployee", description = "", required = true) @Valid @RequestBody OwnerCompanyEmployee ownerCompanyEmployee
    );


    /**
     * POST /owner-company-employees : Create new employee
     *
     * @param ownerCompanyEmployee  (required)
     * @return Created (status code 201)
     */
    @Operation(
        operationId = "ownerCompanyEmployeesPost",
        summary = "Create new employee",
        tags = { "owner_company_employee" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OwnerCompanyEmployee.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/owner-company-employees",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<OwnerCompanyEmployee> ownerCompanyEmployeesPost(
        @Parameter(name = "OwnerCompanyEmployee", description = "", required = true) @Valid @RequestBody OwnerCompanyEmployee ownerCompanyEmployee
    );

}
